fix type defs
Without this change I see errors such as:

```
../file.js:20:23 - error TS2339: Property 'call' does not exist on type 'typeof import("/path/to/node_modules/merge-options/index")'.

20   return mergeOptions.call(
                         ~~~~
```

and

```
../file.js:56:19 - error TS2349: This expression is not callable.
  Type 'typeof import("/path/to/node_modules/merge-options/index")' has no call signatures.

56         options = mergeOptions(constructorOptions.init, options)
                     ~~~~~~~~~~~~
```

and

```
../file.js:8:47 - error TS2339: Property 'bind' does not exist on type 'typeof import("/path/to/node_modules/merge-options/index")'.

8 const mergeOptions = require('merge-options').bind({ ignoreUndefined: true })
                                                ~~~~
```